# include job templates
include:
  - project: 'integrator1/devops/gitlab-ci-jobs'
    ref: master
    file: 'common/test-gradle.gitlab-ci.yml'
  - project: 'integrator1/devops/gitlab-ci-jobs'
    ref: master
    file: 'common/deploy-argocd.gitlab-ci.yml'
  - project: 'integrator1/devops/gitlab-ci-jobs'
    ref: master
    file: 'common/sonarqube.gitlab-ci.yml'
  - project: 'integrator1/devops/gitlab-ci-jobs'
    ref: master
    file: 'common/build-gradle.gitlab-ci.yml'    

stages:
  - tests
  - quality

.artifacts_template: &artifacts
  artifacts:
    expire_in: 1 week
    name: "${CI_COMMIT_SHORT_SHA}_${CI_JOB_ID}"
    reports:
      junit: "**/test-results/test/*.xml"  
    paths:
      - "**/build/reports/detekt/detekt.xml"
      - "**/test-results/test/*.xml"
      - "**/build/jacocoReports/test/jacocoTestReport.xml"
      - images.json  
      - "**/build/libs"

# check code quality 
code_quality:
  extends:
    - .check_code_quality
  only:
    - master
    - dev
    - merge_requests
    - /^.*rc.*$/
    - /^.*release.*$/    
    - /^.*hotfix.*$/
    
tests&build:
  extends:
    - .test-gradle
  script:
    - ./gradlew -PweMavenUser=$MAVEN_USER -PweMavenPassword=$MAVEN_PASSWORD version check build publish
    - ./samples/take_root_version_for_build.sh
  only:
    - dev
    - /^.*rc.*$/
    - /^.*release.*$/    
    - /^.*hotfix.*$/
  <<: *artifacts

tests&build_for_maven_central:
  extends:
    - .test-gradle
  script:
    - cat $we_maven_central_gpg | base64 --decode > "$(pwd)/we_maven_central.gpg"
    - ./gradlew --no-parallel -PsonaTypeMavenUser=$SONATYPE_USER -PsonaTypeMavenPassword=$SONATYPE_PASSWORD -Psigning.keyId=$SIGN_KEY_ID -Psigning.password=$SIGN_PASSWORD -Psigning.secretKeyRingFile="$(pwd)/we_maven_central.gpg" version check build publish
    - ./gradlew -PsonaTypeMavenUser=$SONATYPE_USER -PsonaTypeMavenPassword=$SONATYPE_PASSWORD closeAndReleaseRepository
    - ./samples/take_root_version_for_build.sh
  only:
    - master
  <<: *artifacts

tests-mr:
  extends:
    - .test-mr-gradle
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git fetch origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git config user.email "gitlab-ci@weintegrator.com"
    - git config user.name "GitLab CI WeIntegrator"
    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git pull
    - git merge origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - ./gradlew -PmavenUser=$MAVEN_USER -PmavenPassword=$MAVEN_PASSWORD check build
    - docker images --format "{{json . }}" --no-trunc > images.json
  <<: *artifacts 
